Don't blow up when component is destroyed
When we updated from Ember 2.18 to Ember 3.4 we got a bunch of errors:

> Error: Assertion Failed: Attempted to call .send() with the action
> 'search' on the destroyed object '<dummy@component:power-select::ember1341>'.

This change (borrowed from 8a0583ee8f692541b278f2ddd89d82e531fa543d
upstream) avoids the issue